steps:
#Build diceroller image from google source repository and save image to google container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:${_TAG}', '-f', 'Dockerfile', '.']
  timeout: 180s
  images: "gcr.io/$PROJECT_ID/$REPO_NAME:${_TAG}"

#intialise kubernetes with k8s.yml
#your clould build service account will also need permissions to deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', './k8s/diceroller-deployment.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}' 
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

# build and push the helm image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/helm', '--build-arg', 'HELM_VERSION=v2.10.0', '/helm/.']
  images: ['gcr.io/$PROJECT_ID/helm']


# install chart with helm.
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['install', 'stable/keel', '--name', 'keel', '--namespace', 'keel']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}' 
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'