steps:
#Build diceroller image from google source repository
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:${_TAG}', '-f', 'Dockerfile', '.']
  timeout: 180s

  #push image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:${_TAG}"]
  # This will tag the image with what ever branch it was from. This means that there is no latest image

#intialise kubernetes with k8s.yml
#your clould build service account will also need permissions to deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', './k8s/diceroller-deployment.yml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}' 
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'

# build the helm image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/helm', '--build-arg', 'HELM_VERSION=v2.10.0', './helm/']

  #push image to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/helm"]

  # initalise helm
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['init', '--force-upgrade']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}' 
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'


# install chart with helm.
# TODO set all these config option ina  "values.yaml"
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['install', 'stable/keel', '--namespace', 'kube-system', '--set gcr.enabled="true"', '--set gcr.projectID="$PROJECT_ID"']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}' 
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'