steps:
#Build image from google repo
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:${_TAG}', '-f', 'Dockerfile', '.']
  timeout: 180s

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:${_TAG}"]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - ${_DEPLOYMENT_NAME}
  - ${_CONTAINER}="gcr.io/$PROJECT_ID/$REPO_NAME:${_TAG}"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}' 
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'