version: "3"
services:
  web:
    image: diceroller
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
    #map from host:4000 -> container:9000
      - "4000:9000"
    networks:
      - webnet
networks:
  webnet: