kind: Service
apiVersion: v1
metadata:
  name: diceroller-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: diceroller-deployment
  ports:
  - port: 80
    targetPort: 80