apiVersion: apps/v1
kind: Deployment
metadata:
  name: diceroller-deployment
spec:
  selector:
    matchLabels:
      app: diceroller-deployment
  template:
    metadata:
      labels:
        app: diceroller-deployment
    spec:
      containers:
      - name: diceroller-deployment
        # This image need to be in a public repo.
        image: gcr.io/diceroller-220503/diceroller:master
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.5"

---
kind: Service
apiVersion: v1
metadata:
  name: diceroller-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: diceroller-deployment
  ports:
  - port: 80
    targetPort: 9000

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: diceroller-ingress
spec:
  backend:
    serviceName: diceroller-service
    servicePort: 80
---
# Below is creating a service account for helm to use
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm
    namespace: kube-system